name: azure_app_config_example
description: A Flutter application to demonstrate Azure App Configuration integration.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  azure_app_config: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


